[package]
name = "samase_scarf"
version = "0.1.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[[bin]]
name = "smssl"
required-features = ["binaries"]

[profile.dev]
lto = "no"
codegen-units = 4
opt-level = 2 # Does not worsen compilation times but halves runtime on scarf

[profile.test]
opt-level = 2

[profile.release]
debug = 1
lto = true
overflow-checks = true

[dependencies]
arrayvec = "0.5"
byteorder = "1.1.0"
fxhash = "0.2.1"
log = "0.4"
memchr = "2.0"
memmem = "0.1.1"
quick-error = "1.1.0"
smallvec = "1.0"

fern = { version = "0.5", optional = true }

[dependencies.scarf]
git = "https://github.com/neivv/scarf"
rev = "966474db97b416afd54371cb550a79aaedc47ed6"

[dev-dependencies]
fern = "0.5"

[features]
test_assertions = []
binaries = ['fern']
