[package]
name = "samase_scarf"
version = "0.1.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[dependencies]
arrayvec = "0.5"
byteorder = "1.1.0"
fxhash = "0.2.1"
itertools = "0.8.0"
log = "0.4"
memchr = "2.0"
memmem = "0.1.1"
quick-error = "1.1.0"
smallvec = "1.0"

fern = { version = "0.5", optional = true }

[dependencies.scarf]
git = "https://github.com/neivv/scarf"
rev = "1c609823a10e03ecc9e0d5f3d0a39bd6a3050b3d"

[features]
default = ['binaries']
test_assertions = []
binaries = ['fern']
