[package]
name = "samase_scarf"
version = "0.1.0"
authors = ["Markus Heikkinen <ittevien@gmail.com>"]
edition = "2018"

[[bin]]
name = "dump"
required-features = ["binaries"]

[profile.dev]
lto = "no"
codegen-units = 4
opt-level = 2 # Does not worsen compilation times but halves runtime on scarf

[profile.test]
opt-level = 2

[profile.release]
debug = 1
lto = true
overflow-checks = true

[dependencies]
arrayvec = "0.5"
byteorder = "1.1.0"
fxhash = "0.2.1"
log = "0.4"
memchr = "2.0"
memmem = "0.1.1"
quick-error = "1.1.0"
smallvec = "1.0"

fern = { version = "0.5", optional = true }
anyhow = { version = "1.0", optional = true }
winapi = { version = "0.3", features = ["d3dcompiler"], optional = true }
scopeguard = { version = "1.1", optional = true }

[dependencies.scarf]
git = "https://github.com/neivv/scarf"
rev = "391e53e27383e94ae7c28618dc1e698938ecfdb1"

[dev-dependencies]
fern = "0.5"

[features]
test_assertions = []
binaries = ['fern', 'anyhow', 'winapi', 'scopeguard']
